# 公共配置文件
# @author stephen qiu
spring:
  application:
    name: learning-backend
  # 默认 dev 环境
  config:
    activate:
      on-profile: default
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #   session 配置
  session:
    # 开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${learning.datasource.url}
    username: ${learning.datasource.username}
    password: ${learning.datasource.password}
  # Redis 配置
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # Elasticsearch 配置
  elasticsearch:
    uris: ${learning.elasticsearch.uris}
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
cos:
  client:
    accessKey: ${learning.cos.client.accessKey}
    secretKey: ${learning.cos.client.secretKey}
    region: ${learning.cos.client.region}
    bucket: ${learning.cos.client.bucket}
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    description: "StephenQiu的接口文档信息。"
    concat: "Stephen Qiu"
    email: "learningqhd@gmail.com"
    url: "https://github.com/Stephenqhd30"
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.kc.learning.controller

# 对象存储配置
oss:
  # MinIO OSS配置
  minio:
    # todo 是否开启
    enable: false
    # 域名（格式：【ip:port】）
    endpoint: 127.0.0.1:9000
    # 是否开启TLS
    enable-tls: false
    # 用户的 SecretId
    secret-id: xxxxxxxx
    # 用户的 SecretKey
    secret-key: xxxxxxxx
    # 桶名称
    bucket-name: xxxxxxxx



    
